### ISSUE TITLE
TypeError: res.data.map is not a function

### ISSUE THREAD

**Issue by ianzone** [webflow/js-webflow-api#117]
```
node_modules\.pnpm\webflow-api@1.3.1\node_modules\webflow-api\dist\core\webflow.js:242
        return res.data.map((data) => new api_1.Site(this.client, { ...res, data }));
                        ^
TypeError: res.data.map is not a function
    at Webflow.sites (C:\Users\yihen\Projects\test\webflow\node_modules\.pnpm\webflow-api@1.3.1\node_modules\webflow-api\dist\core\webflow.js:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FnName (C:\Users\yihen\Projects\test\webflow\client.ts:11:16)
```

**Comment by dsinghvi** [comment]
@ianzone what runtime or version of Node are you running on? What endpoint were you calling that caused this error?

**Comment by dsinghvi** [comment]
Looks like you are using the v1 SDK, if you try upgrading to v2 this issue should be fixed!
